### PR TITLE
Feature/fix define stream setter

### PR DESCRIPTION
**Pull request by mindfulmike**

### CODE REVIEW

**Comment by phillipskevin** [comment]
@obaidott @justinbmeyer can this be incorporated into the changes being made in https://github.com/canjs/can-define-stream/pull/29 ?

**Comment by justinbmeyer** [comment]
Yeah, I think this is a good fix.

**Comment by justinbmeyer** [comment]
I just encountered this too.

**Comment by justinbmeyer** [comment]
Thanks for the test, it (and a fix) have been incorporated into https://github.com/canjs/can-define-stream-kefir/blob/master/can-define-stream-kefir_test.js#L186

**Comment by mindfulmike** [comment]
awesome!

**Pull request closed without merging**
